
// auth
export const USER_IS_LOGGING_IN = 'USER_IS_LOGGING_IN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';

// posts
export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE';
export const UPDATE_POST_TITLE = 'UPDATE_POST_TITLE';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_FAILURE = 'UPDATE_POST_FAILURE';
export const SELECT_POST = 'SELECT_POST';
export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';

// blocks
export const ADD_BLOCK = 'ADD_BLOCK';
export const ADD_BLOCK_FAILURE = 'ADD_BLOCK_FAILURE';
export const REMOVE_BLOCK_SUCCESS = 'REMOVE_BLOCK_SUCCESS';
export const REMOVE_BLOCK_FAILURE = 'REMOVE_BLOCK_FAILURE';
export const FETCH_BLOCKS_FAILURE = 'FETCH_BLOCKS_FAILURE';
export const UPDATE_BLOCK_TEXT = 'UPDATE_BLOCK_TEXT';
export const UPDATE_BLOCK_DIALECT = 'UPDATE_BLOCK_DIALECT';
export const FETCH_BLOCKS_SUCCESS = 'FETCH_BLOCKS_SUCCESS';

// sign up
export const FORGOT_PASSWORD_REQUEST = 'forgot_password_request';
export const RESET_PASSWORD_REQUEST = 'reset_password_request';
export const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS';
export const SIGN_UP_USER_FAILURE = 'SIGN_UP_USER_FAILURE';

export const BASE_URL = 'http://localhost:9000';
