
// auth
export const AUTH_IN_PROGRESS = 'USER_IS_LOGGING_IN';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// posts
export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE';
export const UPDATE_POST_TITLE = 'UPDATE_POST_TITLE';
export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';
export const EXPORT_POSTS_FAILURE = 'EXPORT_POSTS_FAILURE';
export const SELECT_POST_BY_NAME_FAILURE = 'SELECT_POST_BY_NAME_FAILURE';
export const SELECT_POSTS_BY_TAG = 'SELECT_POSTS_BY_TAG';
export const SELECT_POST = 'SELECT_POST';

export const UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_FAILURE = 'UPDATE_POST_FAILURE';

// tags
export const ADD_TAG_REQUEST = 'ADD_TAG_REQUEST';
export const ADD_TAG_SUCCESS = 'ADD_TAG_SUCCESS';
export const ADD_TAG_FAILURE = 'ADD_TAG_FAILURE';
export const DELETE_TAG_SUCCESS = 'DELETE_TAG_SUCCESS';
export const DELETE_TAG_FAILURE = 'DELETE_TAG_FAILURE';
export const FETCH_TAGS_REQUEST = 'FETCH_TAGS_REQUEST';
export const FETCH_TAGS_SUCCESS = 'FETCH_TAGS_SUCCESS';
export const FETCH_TAGS_FAILURE = 'FETCH_TAGS_FAILURE';

// blocks
export const UPDATE_BLOCK_FAILURE = 'UPDATE_BLOCK_FAILURE';

export const FETCH_BLOCKS_REQUEST = 'FETCH_BLOCK_REQUEST';
export const FETCH_BLOCKS_FAILURE = 'FETCH_BLOCKS_FAILURE';
export const FETCH_BLOCKS_SUCCESS = 'FETCH_BLOCKS_SUCCESS';


export const BASE_URL = process.env.NODE_ENV === 'production' ? 'https://plog-backend.herokuapp.com' : 'http://localhost:9000';

export const Direction = Object.freeze({
  UP: Symbol('up'),
  DOWN: Symbol('down'),
});
